dev:
  start_time: -600
  metric_name: CPUUtilization
  namespace: AWS/EC2
  period: 300
  statistics: Maximum
  dimensions:
    - name: InstanceId
      value: i-xxxxxxxxxxxxx
  unit: Percent
stg:
  start_time: -600
  metric_name: CPUUtilization
  namespace: AWS/EC2
  period: 300
  statistics: Maximum
  dimensions:
    - name: InstanceId
      value: i-xxxxxxxxxxxxx
  unit: Percent
